In [2]:
!pip install tensorflow scikit-learn

import pandas as pd
import numpy as np
from tensorflow.keras.models import load_model
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder

# Load the data
data = pd.read_csv('fer2013.csv')

# Convert pixels into numpy arrays
data['pixels'] = data['pixels'].apply(lambda pixel_sequence: np.fromstring(pixel_sequence, sep=' ').reshape(48, 48, 1))

# Convert emotion labels to integers
le = LabelEncoder()
data['emotion'] = le.fit_transform(data['emotion'])

# Split the data into train and test sets
train = data[data['Usage'] == 'Training']
test = data[data['Usage'] == 'PublicTest']  # or 'PrivateTest' depending on your dataset

X_test = np.stack(test['pixels'].to_numpy())
y_test = test['emotion'].to_numpy()

# Load the model
model = load_model('_mini_XCEPTION.102-0.66.hdf5')

# Get the model's predictions
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)

# Get the confusion matrix
cm = confusion_matrix(y_test, y_pred_classes)

# Print the confusion matrix
print(cm)



ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
daal4py 2021.6.0 requires daal==2021.4.0, which is not installed.
numba 0.55.1 requires numpy<1.22,>=1.18, but you have numpy 1.24.4 which is incompatible.


     ------------------------------------ 300.8/300.8 MB 529.5 kB/s eta 0:00:00
     ------------------------------------ 442.0/442.0 kB 922.5 kB/s eta 0:00:00
  Using cached keras-2.15.0-py3-none-any.whl (1.7 MB)
  Using cached libclang-16.0.6-py2.py3-none-win_amd64.whl (24.4 MB)
     ---------------------------------------- 3.7/3.7 MB 1.0 MB/s eta 0:00:00
  Using cached termcolor-2.4.0-py3-none-any.whl (7.7 kB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached flatbuffers-23.5.26-py2.py3-none-any.whl (26 kB)
     ------------------------------------ 413.4/413.4 kB 806.2 kB/s eta 0:00:00
  Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
     ------------------------------------ 938.4/938.4 kB 645.9 kB/s eta 0:00:00
     -------------------------------------- 15.8/15.8 MB 669.0 kB/s eta 0:00:00
     ---------------------------------------- 1

RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xe

RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xe

RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xe

SystemError: initialization of _pywrap_checkpoint_reader raised unreported exception

In [3]:
!pip install --upgrade numpy

  Using cached numpy-1.26.4-cp39-cp39-win_amd64.whl (15.8 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.24.4
    Uninstalling numpy-1.24.4:
      Successfully uninstalled numpy-1.24.4


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
daal4py 2021.6.0 requires daal==2021.4.0, which is not installed.
scipy 1.9.1 requires numpy<1.25.0,>=1.18.5, but you have numpy 1.26.4 which is incompatible.
numba 0.55.1 requires numpy<1.22,>=1.18, but you have numpy 1.26.4 which is incompatible.


In [4]:
!pip install --upgrade tensorflow

In [9]:
import pandas as pd
import numpy as np
from tensorflow.keras.models import load_model
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
import cv2


# Load the data
data = pd.read_csv('fer2013.csv')

# Convert pixels into numpy arrays
data['pixels'] = data['pixels'].apply(lambda pixel_sequence: np.fromstring(pixel_sequence, sep=' ').reshape(48, 48, 1))

# Convert emotion labels to integers
le = LabelEncoder()
data['emotion'] = le.fit_transform(data['emotion'])

# Split the data into train and test sets
train = data[data['Usage'] == 'Training']
test = data[data['Usage'] == 'PublicTest']  # or 'PrivateTest' depending on your dataset

X_test = np.stack(test['pixels'].to_numpy())
# Resize the images
X_test_resized = np.array([cv2.resize(img, (64, 64)) for img in X_test])
y_test = test['emotion'].to_numpy()

# Load the model
model = load_model('_mini_XCEPTION.102-0.66.hdf5')

# Get the model's predictions

# Now use X_test_resized instead of X_test to make predictions
y_pred = model.predict(X_test_resized)
y_pred_classes = np.argmax(y_pred, axis=1)

# Get the confusion matrix
cm = confusion_matrix(y_test, y_pred_classes)

# Print the confusion matrix
print(cm)

from sklearn.metrics import accuracy_score

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred_classes)

# Print accuracy
print(f'Accuracy: {accuracy * 100:.2f}%')



113/113 [==============================] - 5s 30ms/step
[[465   0   1   0   0   0   1]
 [ 56   0   0   0   0   0   0]
 [494   0   2   0   0   0   0]
 [893   0   2   0   0   0   0]
 [652   0   1   0   0   0   0]
 [413   0   2   0   0   0   0]
 [604   0   1   2   0   0   0]]
Accuracy: 13.01%


In [7]:
! pip install opencv-python

  Using cached opencv_python-4.9.0.80-cp37-abi3-win_amd64.whl (38.6 MB)
